### ISSUE TITLE
Documentation of CRecordset::Open needs hyperlink

### ISSUE THREAD

**Issue by feraudyh** [MicrosoftDocs/cpp-docs.fr-fr#15]
The following text

For more information about this string, see the table and the discussion of ClassWizard's role under Remarks.

left me confused. Maybe a hyperlink would help to know where to look.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 71164027-2c34-9866-08c8-8ceef252b0a8
* Version Independent ID: 9a2b95ed-065d-cb52-29e5-669d232230c0
* Content: [CRecordset, classe](https://docs.microsoft.com/fr-fr/cpp/mfc/reference/crecordset-class?view=vs-2019#feedback)
* Content Source: [docs/mfc/reference/crecordset-class.md](https://github.com/MicrosoftDocs/cpp-docs.fr-fr/blob/live/docs/mfc/reference/crecordset-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by srvbpigh** [comment]
Hello, @feraudyh
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @feraudyh 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/cpp-docs/issues/1656

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
